name: Rust

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        BUILD_TARGET: [release]

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Build
      run: cargo build --profile ${{ matrix.BUILD_TARGET }} --verbose
    - name: Run tests
      run: cargo test --profile ${{ matrix.BUILD_TARGET }} --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: icoutils-rs-ubuntu-24.04-amd64
        path: target/${{ matrix.BUILD_TARGET }}/icotool


  cross-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        BUILD_TARGET: [release]
        BUILD_TRIPLE: [x86_64-unknown-linux-gnu]
        GLIBC_VERSION: [2.28]

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Install cargo-zigbuild via pip
      run: pip install cargo-zigbuild
    - name: Cross Build
      run: cargo zigbuild --profile ${{ matrix.BUILD_TARGET }} --verbose --target ${{ matrix.BUILD_TRIPLE }}.${{ matrix.GLIBC_VERSION }}
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: icoutils-rs-${{ matrix.BUILD_TRIPLE }}
        path: target/${{ matrix.BUILD_TRIPLE }}/${{ matrix.BUILD_TARGET }}/icotool

  windows-build:
    runs-on: windows-2022
    strategy:
      matrix:
        BUILD_TARGET: [release]

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Build
      run: cargo build --profile ${{ matrix.BUILD_TARGET }} --verbose
    - name: Run tests
      run: cargo test --profile ${{ matrix.BUILD_TARGET }} --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: icoutils-rs-windows-2022-x86_64
        path: |
          target/${{ matrix.BUILD_TARGET }}/icotool.exe
          target/${{ matrix.BUILD_TARGET }}/icotool.pdb
